/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package validacpf;

import java.lang.reflect.Array;

/**
 *
 * @author Preto
 */
public class GuiValidaCpf extends javax.swing.JFrame {

    /**
     * Creates new form GuiValidaCpf
     */
    char cpf[],num[];
    int i,j,ver,soma,d1,d2;
    
    public GuiValidaCpf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldValorVer = new javax.swing.JTextField();
        jLabelTxtVer = new javax.swing.JLabel();
        jButtonLimpaVer = new javax.swing.JButton();
        jButtonAcaoVer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValorGer = new javax.swing.JTextField();
        jLabelTxtGer = new javax.swing.JLabel();
        jButtonLimpaGer = new javax.swing.JButton();
        jButtonAcaoGer = new javax.swing.JButton();
        jTextFieldValorCpfGer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valida CPF", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Digite apenas os 11 dígitos do CPF:");

        jLabelTxtVer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTxtVer.setText("Digite o CPF!");
        jLabelTxtVer.setToolTipText("");
        jLabelTxtVer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonLimpaVer.setText("Limpar");
        jButtonLimpaVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaVerActionPerformed(evt);
            }
        });

        jButtonAcaoVer.setText("Verificar");
        jButtonAcaoVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcaoVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTxtVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldValorVer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButtonLimpaVer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAcaoVer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorVer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTxtVer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLimpaVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAcaoVer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Verificar CPF", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Digite 9 números:");

        jLabelTxtGer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTxtGer.setText("Digite os 9 números!");
        jLabelTxtGer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonLimpaGer.setText("Limpar");
        jButtonLimpaGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaGerActionPerformed(evt);
            }
        });

        jButtonAcaoGer.setText("Gerar");
        jButtonAcaoGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcaoGerActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF Gerado:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldValorCpfGer, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jButtonLimpaGer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAcaoGer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTxtGer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldValorGer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorGer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTxtGer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorCpfGer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLimpaGer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAcaoGer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Gerar Dígitos Verificadores", jPanel4);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-447)/2, 416, 447);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpaGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaGerActionPerformed
        jTextFieldValorGer.setText("");
        jTextFieldValorCpfGer.setText("");
        jLabelTxtGer.setText("Digite os 9 números!");
        jTextFieldValorGer.requestFocus();
    }//GEN-LAST:event_jButtonLimpaGerActionPerformed

    private void jButtonLimpaVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaVerActionPerformed
        jTextFieldValorVer.setText("");
        jLabelTxtVer.setText("Digite o CPF!");
        jTextFieldValorVer.requestFocus();
    }//GEN-LAST:event_jButtonLimpaVerActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAcaoGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcaoGerActionPerformed
        cpf = jTextFieldValorGer.getText().toCharArray(); 
        ver = 0;
        num = "0123456789".toCharArray();
        
        if(jTextFieldValorGer.getText().equals("")) {
            jLabelTxtGer.setText("Digite os 9 números!");
            jTextFieldValorGer.requestFocus();
        } else if(jTextFieldValorGer.getText().length()<9 || jTextFieldValorGer.getText().length()>9) {
            jLabelTxtGer.setText("Você precisa digitar 9 números!");
            jTextFieldValorGer.requestFocus();        
        } else {
            for(i=0;i<9;i++) {
                for(j=0;j<10;j++) {
                    if(String.valueOf(cpf[i]).equals(String.valueOf(num[j]))) {
                        ver++;
                        break;
                    } else {
                        continue;
                    }
                }
            }
            
            if(ver<9) {
                jLabelTxtGer.setText("Digite apenas números!");
                jTextFieldValorGer.requestFocus();
            } else {
                for(i=10;i>1;i--) {
                    soma = soma+(Integer.parseInt(String.valueOf(cpf[10-i]))*i);
                }

                d1 = soma%11;
                soma = 0;

                if(d1<2)
                    d1 = 0;
                else
                    d1 = 11-d1;

                for(i=11;i>1;i--) {
                    if(i>2)
                        soma = soma+(Integer.parseInt(String.valueOf(cpf[11-i]))*i);
                    else
                        soma = soma+d1*i;
                }

                d2 = soma%11;
                soma = 0;

                if(d2<2)
                    d2 = 0;
                else
                    d2 = 11-d2;

                jLabelTxtGer.setText("Os dígitos verificadores são: "+String.valueOf(d1)+" e "+String.valueOf(d2));
                jTextFieldValorCpfGer.setText(String.valueOf(cpf)+String.valueOf(d1)+String.valueOf(d2));
                jTextFieldValorCpfGer.requestFocus();
            }
           
        }
    }//GEN-LAST:event_jButtonAcaoGerActionPerformed

    private void jButtonAcaoVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcaoVerActionPerformed
        cpf = jTextFieldValorVer.getText().toCharArray(); 
        ver = 0;
        num = "0123456789".toCharArray();
        
        if(jTextFieldValorVer.getText().equals("")) {
            jLabelTxtVer.setText("Digite o CPF!");
            jTextFieldValorVer.requestFocus();
        } else if(jTextFieldValorVer.getText().length()<11 || jTextFieldValorVer.getText().length()>11) {
            jLabelTxtVer.setText("O CPF precisa ter 11 dígitos!");
            jTextFieldValorVer.requestFocus();
        } else {
            for(i=0;i<11;i++) {
                for(j=0;j<10;j++) {
                    if(String.valueOf(cpf[i]).equals(String.valueOf(num[j]))) {
                        ver++;
                        break;
                    } else {
                        continue;
                    }
                }
            }
            
            if(ver<11) {
                jLabelTxtVer.setText("Digite apenas números!");
                jTextFieldValorVer.requestFocus();
            } else {
                for(i=10;i>1;i--) {
                    soma = soma+(Integer.parseInt(String.valueOf(cpf[10-i]))*i);
                }

                d1 = soma%11;
                soma = 0;

                if(d1<2)
                    d1 = 0;
                else
                    d1 = 11-d1;

                for(i=11;i>1;i--) {
                    if(i>2)
                        soma = soma+(Integer.parseInt(String.valueOf(cpf[11-i]))*i);
                    else
                        soma = soma+d1*i;
                }

                d2 = soma%11;
                soma = 0;

                if(d2<2)
                    d2 = 0;
                else
                    d2 = 11-d2;

                if(Integer.parseInt(String.valueOf(cpf[9]))==d1 && Integer.parseInt(String.valueOf(cpf[10]))==d2)
                    jLabelTxtVer.setText("O CPF: "+String.valueOf(cpf)+" é VÁLIDO!");
                else
                    jLabelTxtVer.setText("O CPF: "+String.valueOf(cpf)+" é INVÁLIDO!");
            }
        }
        
    }//GEN-LAST:event_jButtonAcaoVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiValidaCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiValidaCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiValidaCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiValidaCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GuiValidaCpf().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcaoGer;
    private javax.swing.JButton jButtonAcaoVer;
    private javax.swing.JButton jButtonLimpaGer;
    private javax.swing.JButton jButtonLimpaVer;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTxtGer;
    private javax.swing.JLabel jLabelTxtVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldValorCpfGer;
    private javax.swing.JTextField jTextFieldValorGer;
    private javax.swing.JTextField jTextFieldValorVer;
    // End of variables declaration//GEN-END:variables
}
